# Docker Compose 配置文件 - 群晖系统专用
# 此配置文件专门为群晖 NAS 系统优化，解决权限问题

version: '3.8'

services:
  emby-actor-processor:
    # build: .
    # 使用预构建的镜像:
    image: NasPilot/emby-actor-processor:latest
    
    container_name: emby-actor-processor
    
    # ✨✨✨ 群晖系统权限配置 ✨✨✨
    environment:
      # 群晖默认管理员用户的 UID/GID
      - PUID=1026             # 群晖管理员用户 ID
      - PGID=100              # 群晖 users 组 ID  
      - UMASK=022             # 文件权限掩码
      - TZ=Asia/Shanghai      # 时区设置
      - AUTH_USERNAME=admin   # 自定义登录账号
    
    # 网络模式配置 (可选择 bridge 或 host)
    # bridge: 默认模式，使用端口映射
    # host: 直接使用宿主机网络，性能更好但端口冲突风险更高
    network_mode: bridge
    
    # 端口映射 (仅在 bridge 模式下生效)
    ports:
      - "5257:5257"
    
    # 数据卷挂载
    volumes:
      # 配置和数据目录 - 确保此目录对 UID 1026 有写权限
      - /volume1/docker/emby-actor-processor:/config
      # 如果需要访问 Emby 的本地数据（可选）
      # - /volume1/emby/metadata:/emby-data:ro
    
    # 重启策略
    restart: unless-stopped
    
    # 网络配置（如果需要）
    # networks:
    #   - emby-network

# 如果需要自定义网络
# networks:
#   emby-network:
#     driver: bridge

# 注意事项：
# 1. 请确保 /volume1/docker/emby-actor-processor 目录存在
# 2. 该目录应该对 UID 1026 (群晖管理员) 有读写权限
# 3. 如果使用不同的用户，请相应调整 PUID 值
# 4. 首次运行前，建议手动创建目录并设置权限：
#    sudo mkdir -p /volume1/docker/emby-actor-processor
#    sudo chown 1026:100 /volume1/docker/emby-actor-processor
#    sudo chmod 755 /volume1/docker/emby-actor-processor